# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joyous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoCalendarPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'verbose_name': 'Calendar Demo',
            },
            bases=('joyous.calendarpage',),
        ),
    ]
