# Generated by Django 2.2.6 on 2019-10-24 21:49

from django.db import migrations, models
import django.db.models.deletion
import ls.joyous.utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('joyous', '0015_auto_20190409_0645'),
        ('events', '0002_tagsdemopage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoMultidayEventPage',
            fields=[
                ('multidayeventpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='joyous.MultidayEventPage')),
                ('organizer', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('joyous.multidayeventpage',),
        ),
        migrations.CreateModel(
            name='DemoPostponementPage',
            fields=[
                ('postponementpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='joyous.PostponementPage')),
                ('organizer', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('joyous.postponementpage',),
        ),
        migrations.CreateModel(
            name='DemoRecurringEventPage',
            fields=[
                ('recurringeventpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='joyous.RecurringEventPage')),
                ('organizer', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('joyous.recurringeventpage',),
        ),
        migrations.CreateModel(
            name='DemoSimpleEventPage',
            fields=[
                ('simpleeventpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='joyous.SimpleEventPage')),
                ('organizer', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('joyous.simpleeventpage',),
        ),
        migrations.CreateModel(
            name='DemoCancellationPage',
            fields=[
            ],
            options={
                'indexes': [],
                'constraints': [],
                'proxy': True,
            },
            bases=(ls.joyous.utils.mixins.ProxyPageMixin, 'joyous.cancellationpage'),
        ),
        migrations.CreateModel(
            name='DemoExtraInfoPage',
            fields=[
            ],
            options={
                'indexes': [],
                'constraints': [],
                'proxy': True,
            },
            bases=(ls.joyous.utils.mixins.ProxyPageMixin, 'joyous.extrainfopage'),
        ),
    ]
