# Generated by Django 2.2.6 on 2019-10-25 00:32

from django.db import migrations
import django.db.models.manager
import ls.joyous.utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_democancellationpage_demoextrainfopage_demomultidayeventpage_demopostponementpage_demorecurringevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoMultidayRecurringEventPage',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'constraints': [],
            },
            bases=(ls.joyous.utils.mixins.ProxyPageMixin, 'events.demorecurringeventpage'),
            managers=[
                ('events', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DemoRescheduleMultidayEventPage',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'constraints': [],
            },
            bases=(ls.joyous.utils.mixins.ProxyPageMixin, 'events.demopostponementpage'),
            managers=[
                ('events', django.db.models.manager.Manager()),
            ],
        ),
    ]
