# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlainPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.RichTextField(blank=True, default='', help_text='An area of text for whatever you like')),
            ],
            options={
                'verbose_name': 'Plain Text Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
