"""
Django settings for demo project.

Generated by "django-admin startproject" using Django 1.11.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

from __future__ import absolute_import, unicode_literals

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "home",
    "search",
    "events",
    "website",
    "dashboard",

    "ls.joyous",
    "wagtail.contrib.modeladmin",
    "wagtail.contrib.postgres_search",

    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail.core",

    "modelcluster",
    "taggit",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",

    "wagtail.core.middleware.SiteMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",

    "ls.joyous.middleware.UserTimeZoneMiddleware",
]

ROOT_URLCONF = "demo.urls"

TEMPLATES = [
    {
        'BACKEND': "django.template.backends.django.DjangoTemplates",
        'DIRS': [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "demo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

#DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.sqlite3",
#        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
#    }
#}


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

FORMAT_MODULE_PATH = "demo.formats"
LANGUAGE_CODE = "en-nz"
TIME_ZONE = "Pacific/Auckland"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, "static"),
]


STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

WAGTAIL_SITE_NAME = "Demo"

WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': "wagtail.contrib.postgres_search.backend",
        'SEARCH_CONFIG': "english",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don"t include "/admin" or a trailing slash
BASE_URL = "http://demo.linuxsoftware.nz"

ALLOWED_HOSTS = ["demo.linuxsoftware.nz", ".localhost", "127.0.0.1", "[::1]"]

JOYOUS_HOLIDAYS = "NZ[*]"
JOYOUS_GROUP_SELECTABLE = True
JOYOUS_TIME_INPUT = 12
JOYOUS_THEME_CSS = "/static/joyous/css/joyous_coast_theme.css"

JOYOUS_DATE_FORMAT = "l jS \\o\\f F X"
JOYOUS_DATE_SHORT_FORMAT = "j F Y"
JOYOUS_TIME_FORMAT = "fq"

from contextlib import suppress
from django.utils.translation import get_language_info
def _nameLocal(lang, name=""):
    with suppress(KeyError):
        name = get_language_info(lang)['name_local'].title()
    return (lang, name)

LANGUAGES = WAGTAILADMIN_PERMITTED_LANGUAGES = [
              ("en-au",  "English (Australia)"),
              ("en-nz",  "English (NZ)"),
              ("en-gb",  "English (UK)"),
              ("en",     "English (USA)"),
    _nameLocal("fr",     "French"),
    _nameLocal("de",     "German"),
    _nameLocal("el",     "Greek"),
    _nameLocal("it",     "Italian"),
    _nameLocal("ja",     "Japanese"),
    _nameLocal("pt-br",  "Portuguese (Brazil)"),
]
